### PR TITLE
feat: add go support

### PR DESCRIPTION
**Pull request by BelfordZ**
for the following open rpc document in ./openrpc.json
```json
{
  "info": {
    "title": "jipperjobber",
    "version": "3.2.1"
  },
  "methods": [
    {
      "name": "jibber",
      "params": [
        {
          "name": "jibberNiptip",
          "schema": {
            "description": "a really cool niptip",
            "title": "niptip",
            "type": "number"
          }
        }
      ],
      "result": {
        "name": "jibberRipslip",
        "schema": {
          "properties": {
            "reepadoop": {
              "type": "number"
            },
            "skeepadeep": {
              "title": "skeepadeep",
              "type": "integer"
            }
          },
          "title": "ripslip",
          "type": "object"
        },
      }
    }
  ],
  "openrpc": "1.0.0"
}
```

the following command 

```bash
open-rpc-typings --name-go jipperjobber --output-go ./generated-types
```

will produce the following file:
```golang
// a really cool niptip
type Niptip float64
type Skeepadeep int64
type NumberYqdpe1HS float64
type Ripslip struct {
  Reepadoop  *float64 `json:\"reepadoop\"`
  Skeepadeep *int64   `json:\"skeepadeep\"`
}
type Jipperjobber interface {
  Jibber(jibberNiptip Niptip) (error, Ripslip)
}
```

The ts interface to this package has more configs to enable / disable the printing of the interface, as well as others.

### CODE REVIEW

**Comment by BelfordZ** [comment]
@tzdybal would love a review from you :)

**Comment by BelfordZ** [comment]
also, dont worry about test coverage drop. I need to do an update to the rust typings gen at some point, and the coverage will be had from that.

**Comment by BelfordZ** [comment]
I think we need to spice up the cli to make things a bit more configurable, with all the options of the ts interface

**Comment by shanejonas** [comment]
resident quicktype mangler 😂

**Pull request merged**
